### ISSUE TITLE
Add method that replace old roles by new roles

### ISSUE THREAD

**Issue by HatemJerbi** [alanning/meteor-roles#198] opened 2016-05-06 22:12 UTC
Take the example when we have a form where admin assign roles to specific user by group of check box.
the method Roles.setUserRoles can't handle this situation because it add new assigned roles and didn't delete unassigned roles.
thxs

**Comment by mitar** [comment] 2016-05-06 22:17
Duplicate of #197.

**Closed by mitar** 2016-05-06 22:17 UTC
