### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by dr-dimitru** [alanning/meteor-roles#132] opened 2015-09-27 19:30 UTC
For example he have a user (which is not in any group (except `Roles.GLOBAL_GROUP` of course)):
```json
{
  "_id": "3z4WHQsH8jFkKSx6v",
  "emails": [
    {
      "address": "demo@example.com",
      "verified": false
    }
  ],
  "profile": {},
  "username": "demo@example.com",
  "roles": {
    "__global_roles__": [
      "regular"
    ]
  }
}
```

When I run:
```js
Roles.userIsInRole(Meteor.userId(), ['admin', 'regular'], 'admins')) // Returns `true`, expected `false`
Roles.userIsInRole(Meteor.userId(), ['admin', 'regular'], Roles.GLOBAL_GROUP)) // Returns `true`, okay
Roles.userIsInRole(Meteor.userId(), ['admin', 'regular'], undefined)) // Returns `true`, okay
```

First statement expected to be `false` as user isn't at `admins` group

**Comment by dr-dimitru** [comment] 2015-09-27 20:10
One more inconvenience, now I have user in  `regular` and `admin` roles, and in `admins` group:
```json
{
  "_id": "fqot2Dxzx9G64EFev",
  "emails": [
    {
      "address": "admin@example.com",
      "verified": false
    }
  ],
  "profile": {},
  "username": "admin@example.com",
  "roles": {
    "admins": [
      "regular",
      "admin"
    ]
  }
}
```
When I run:
```js
Roles.userIsInRole(Meteor.userId(), ['admin', 'regular'], 'admins')) // Returns `true`, okay
Roles.userIsInRole(Meteor.userId(), ['admin', 'regular'], Roles.GLOBAL_GROUP)) // Returns `false`, okay
Roles.userIsInRole(Meteor.userId(), ['admin', 'regular'], undefined)) // Returns `false`, expected `true`
Roles.userIsInRole(Meteor.userId(), ['admin'], undefined)) // Returns `false`, expected `true`
Roles.userIsInRole(Meteor.userId(), 'admin', undefined)) // Returns `false`, expected `true`
```

**Comment by alanning** [comment] 2015-10-05 08:07
Regarding the first case, the results you reported are the expected behavior.  Roles.GLOBAL_GROUP is special in that it will always be checked.  It's convenient when you have some kind of permissions that should apply irrespective of groups, such as super-user privileges for your customer support employees.

Regarding the second case, that is also the expected behavior.  Groups are like storage containers for permissions.  When you do the `Roles. userIsInRole` check, if the container name doesn't have the permission you are checking for, then it returns false.  If you want it to return 'true' regardless of what group you pass in then you should add the permission to the `Roles.GLOBAL_GROUP` group.

Closing this issue but feel free to ask further questions if you'd still like help.

**Closed by alanning** 2015-10-05 08:07 UTC

**Comment by dr-dimitru** [comment] 2015-10-05 19:43
Thank you for reply, is there any way to check user for group participation without checking the role? Like:
```js
Roles.userIsInRole(Meteor.userId(), [], 'admins'))
// or
Roles.userIsInGroup(Meteor.userId(), 'admins'))
```

As group rights has higher priority over role, it is useless to check for role in most cases (*only my experience*)

**Comment by alanning** [comment] 2015-10-05 21:05
I think the intended use is still a bit different from how you are
envisioning it. Testing that a user is in a group would probably not be
very meaningful until you attach a role to it.

For example, we have users in "networks" and in each "network" they can
have specific permissions. In our publish function for network info, the
user will pass which network they are trying to access data for and we will
check if they have the right permissions to see that data. But we check for
that permission in the context of just the group they want. They might have
read permissions for one network (group) but read and write in another
network (group).

So just checking that they have -some- permission in a group is not useful.
We need to check for a specific permission depending on what action they
are trying to take.

If you don't need your users to have separate permission for different
groups, you can just not use groups. Give your admins the "admin"
permission and just check for that.

**Comment by dr-dimitru** [comment] 2015-10-06 05:14
Got it, but still confused. Thank you for detailed answer.

**Comment by alanning** [comment] 2015-10-06 23:38
Can you tell me about your use case?  I may be able to suggest an appropriate usage.

**Comment by dr-dimitru** [comment] 2015-10-07 08:53
@alanning this is my use case: [iron-router-protected](https://github.com/VeliovGroup/Meteor-iron-router-protected/blob/master/iron-router-protected.coffee#L52)
I'm not sure if I'm checking this correctly.
Should I set `Roles.GLOBAL_GROUP` by default if `allowedGroup` is not set for router?

**Comment by dr-dimitru** [comment] 2015-10-07 08:55
I though I it will be good to check on some routes for group only

**Comment by alanning** [comment] 2015-10-17 15:36
In your demo, you aren't partitioning users into different, independent buckets so you should not use groups.  

Just do:  `Roles.addUsersToRoles demo, ['regular']` and `Roles.addUsersToRoles admin, ['regular', 'admin']`

In the protected Iron Router [here](https://github.com/VeliovGroup/Meteor-iron-router-protected/blob/master/iron-router-protected.coffee#L52), you need to also check to see if the user defined an `allowedGroup`.  If not, use the non-group version of the `Roles.userIsInRole` check.

**Comment by dr-dimitru** [comment] 2015-10-19 21:08
@alanning I believe is what we doing, if user not defined `allowedGroup`, we set `@allowedGroup` to `undefined` and run: 
```coffeescript
Roles.userIsInRole(Meteor.userId(), @allowedRoles, @allowedGroup)
```

**Comment by dr-dimitru** [comment] 2015-10-19 21:11
> In your demo, you aren't partitioning users into different, independent buckets so you should not use groups.

But I need to check and show `allowedGroup` functionality somehow

**Comment by alanning** [comment] 2015-10-30 19:55
> I believe is what we doing, if user not defined allowedGroup, we set @allowedGroup to undefined

OK, that should work.

> But I need to check and show allowedGroup functionality somehow

So the demo doesn't use groups but you still want to support them in the library, is that right?

The thing is that the usage of groups is ultimately determined by the user's account rather than the route.  You could have a user which uses groups trying to access a route which does not have @allowedGroup.  In that case the check will fail because you'll be using the non-group version of the func but the user account uses groups.  (This is because the database structure is different; groups uses an object hash while non-groups uses a straight array.)
