### ISSUE TITLE
getGroupsForUser - [role] being treated as mutually exclusive

### ISSUE THREAD

**Issue by romant** [alanning/meteor-roles#170] opened 2016-01-24 09:11 UTC
documentation relates :

>[role] String optional
>Optional name of roles to restrict groups to.

Yet trying it with a user that belongs to a group; upon which I then query `Roles.getGroupsForUser('mCE2dx2n964MbLjPi', ['oger','minion'])` results in an empty `[]`

Whilst the same query for a single role 
```
Roles.getGroupsForUser('mCE2dx2n964MbLjPi', 'minion')
```

Returns the expected array of Groups.

I notice that the [code](https://github.com/alanning/meteor-roles/blob/master/roles/roles_common.js#L520-L523) actually does iterate over all the `groupRoles` - but in this case - actually returns an empty array.

Any pointers on debugging?

Many thanks.

**Comment by miri-am** [comment] 2016-01-27 00:07
Looks like ```role```needs to be a String: http://alanning.github.io/meteor-roles/files/roles_roles_common.js.html#l485
The code iterates over user.roles but not role.

**Comment by alanning** [comment] 2016-01-27 01:13
Yes, currently that function requires a single string.  I think you may be confused by the jsdoc syntax;  in this case brackets around the parameter name indicate that the parameter is optional.  If the parameter accepts a String or an Array, the format would be:

`* @param {Array|String} role Name of role/permission...`

- http://alanning.github.io/meteor-roles/files/roles_roles_common.js.html#l427

**Comment by romant** [comment] 2016-01-27 09:10
Thank you @alanning. That's helpful.

Don't suppose any plans underway to add array of strings support ? Or is focus on v.2 ? In which case - what's the plan for behaviour there for a multiple role check?

**Comment by mitar** [comment] 2016-02-01 05:40
This is a duplicate of #140 for which there was a pull request #148.

In v2.0 this is already implemented.

**Comment by mitar** [comment] 2016-02-01 05:41
See also tests in c07767d6e0c792e774a156788ee5fad52163c2d3 to see if that covers your use case.

**Closed** 2016-02-01 05:41 UTC

**Comment by romant** [comment] 2016-02-01 05:42
Thank you @mitar. What's the eta for v2.0 ?

**Comment by mitar** [comment] 2016-02-01 05:43
See #165 for the discussion on the topic. You can also try it out in v2.0 branch. I think most things are ready, but it needs more testing by users so that we see if everything works as expected.
