### ISSUE TITLE
add user  roles by group is error

### ISSUE THREAD

**Issue by jinzhiqiang** [alanning/meteor-roles#108] opened 2015-05-28 06:34 UTC
add to group error
version 1.2.13
roles publis to client ok
and setuserRoles error:
Roles.addUsersToRoles( userid,'aaa','group')
error msg:When the modifier option is true, validation object must have at least one operator

and no group is ok
Roles.addUsersToRoles( userid,'aaa')

help me:)

**Comment by alanning** [comment] 2015-05-30 01:18
I think what's happening is that the user is already set up for non-groups.

Groups are an all-or-nothing thing with the roles package due to the way the data is stored.  With groups, the data is stored in an object but if you set a role on a user without groups first, the data will be stored in an array.  You can see an example of this described here: https://github.com/alanning/meteor-roles#user-content-changes

I'd check the user and remove the roles object, then try adding again.

If you have "global" groups that should apply to the user across all groups, you can use the special group  `Roles.GLOBAL_GROUP` like this:

`Roles.addUsersToRoles(userId, 'aaa', Roles.GLOBAL_GROUP)`

**Comment by alanning** [comment] 2015-10-05 07:37
Just released v1.2.14 which improves the error message when attempting to mix groups and non-groups.  I'm closing this issue for now but please re-open if you'd like more help.

**Closed by alanning** 2015-10-05 07:37 UTC

**Comment by shailendra735** [comment] 2015-12-09 10:06
I have this same issue. I've made sure that no user is set for any non-group. In fact, I've tried making all the users part of one global group. But no luck.
Any suggestions?

**Comment by alanning** [comment] 2015-12-13 08:37
@shailendra735, can you put up a simple github repo which reproduces the error message?  If so, I can analyze further to figure out what's going on.
